// Code generated by protoc-gen-go. DO NOT EDIT.
// source: req.proto

package req

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Meta struct {
	Node                 string   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_req_c2136dd6d8099ec3, []int{0}
}
func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (dst *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(dst, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Meta) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Meta) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type DRequest struct {
	Meta                 *Meta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ReqId                string   `protobuf:"bytes,2,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Params               []byte   `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DRequest) Reset()         { *m = DRequest{} }
func (m *DRequest) String() string { return proto.CompactTextString(m) }
func (*DRequest) ProtoMessage()    {}
func (*DRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_req_c2136dd6d8099ec3, []int{1}
}
func (m *DRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DRequest.Unmarshal(m, b)
}
func (m *DRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DRequest.Marshal(b, m, deterministic)
}
func (dst *DRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DRequest.Merge(dst, src)
}
func (m *DRequest) XXX_Size() int {
	return xxx_messageInfo_DRequest.Size(m)
}
func (m *DRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DRequest proto.InternalMessageInfo

func (m *DRequest) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *DRequest) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *DRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DRequest) GetParams() []byte {
	if m != nil {
		return m.Params
	}
	return nil
}

type DResponse struct {
	Meta                 *Meta    `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ReqId                string   `protobuf:"bytes,2,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DResponse) Reset()         { *m = DResponse{} }
func (m *DResponse) String() string { return proto.CompactTextString(m) }
func (*DResponse) ProtoMessage()    {}
func (*DResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_req_c2136dd6d8099ec3, []int{2}
}
func (m *DResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DResponse.Unmarshal(m, b)
}
func (m *DResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DResponse.Marshal(b, m, deterministic)
}
func (dst *DResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DResponse.Merge(dst, src)
}
func (m *DResponse) XXX_Size() int {
	return xxx_messageInfo_DResponse.Size(m)
}
func (m *DResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DResponse proto.InternalMessageInfo

func (m *DResponse) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *DResponse) GetReqId() string {
	if m != nil {
		return m.ReqId
	}
	return ""
}

func (m *DResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Meta)(nil), "Meta")
	proto.RegisterType((*DRequest)(nil), "DRequest")
	proto.RegisterType((*DResponse)(nil), "DResponse")
}

func init() { proto.RegisterFile("req.proto", fileDescriptor_req_c2136dd6d8099ec3) }

var fileDescriptor_req_c2136dd6d8099ec3 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0xbf, 0x8a, 0xc2, 0x40,
	0x10, 0x87, 0xc9, 0x65, 0x13, 0x2e, 0x73, 0x29, 0x8e, 0x85, 0x3b, 0xd6, 0x2e, 0xa4, 0x4a, 0x95,
	0x42, 0xdf, 0x40, 0x82, 0x60, 0x61, 0xe1, 0x96, 0x36, 0xb2, 0xb2, 0x23, 0x11, 0x49, 0x36, 0xfb,
	0xc7, 0xc2, 0xb7, 0x97, 0x1d, 0xf7, 0x09, 0xec, 0xbe, 0xf9, 0x8a, 0xdf, 0x07, 0x03, 0x95, 0x43,
	0xdb, 0x2f, 0xce, 0x04, 0xd3, 0xee, 0x80, 0x1d, 0x30, 0x28, 0xce, 0x81, 0xcd, 0x46, 0xa3, 0xc8,
	0x9a, 0xac, 0xab, 0x24, 0x71, 0x74, 0xa3, 0xf1, 0x41, 0x7c, 0xbd, 0x5d, 0x64, 0xfe, 0x0f, 0xe5,
	0x84, 0x61, 0x34, 0x5a, 0xe4, 0x64, 0xd3, 0xd5, 0x5e, 0xe1, 0x7b, 0x90, 0x68, 0x1f, 0xe8, 0x03,
	0x5f, 0x01, 0x9b, 0x30, 0x28, 0xda, 0xfa, 0x59, 0x17, 0x7d, 0x0c, 0x48, 0x52, 0xfc, 0x0f, 0x4a,
	0x87, 0xf6, 0x7c, 0xd3, 0x69, 0xb4, 0x70, 0x68, 0xf7, 0x9a, 0xff, 0x42, 0x7e, 0xc7, 0x67, 0x9a,
	0x8c, 0x18, 0x3b, 0x8b, 0x72, 0x6a, 0xf2, 0x82, 0x35, 0x59, 0x57, 0xcb, 0x74, 0xb5, 0x47, 0xa8,
	0x06, 0x89, 0x7e, 0x31, 0xb3, 0xc7, 0x0f, 0x42, 0x1c, 0x98, 0x56, 0x41, 0x51, 0xa9, 0x96, 0xc4,
	0xdb, 0xe2, 0x94, 0x3b, 0xb4, 0x97, 0x92, 0x1e, 0xb2, 0x79, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd1,
	0x80, 0x75, 0xf6, 0x1d, 0x01, 0x00, 0x00,
}
